export const projects = {

  "exclusive-ecom": {
    name: "Exclusive E-Commerce",
    year: "2025",
    image: "/projects/e-com.webp",
    link: "https://exclusive-e-com-rasil.vercel.app/",
    description: "This project is a fully responsive e-commerce platform built with React 19, showcasing a sleek UI and smooth user experience. Users can browse dynamic product pages, manage a shopping cart, and enjoy advanced filtering. A unique checkout animation enriches interactivity. I implemented responsive design, reusable components, and state management using Context API. The site supports multiple product categories and is deployed on Vercel. Overall, this modern e-commerce site combines performance, clean aesthetics, and animation to provide a seamless shopping experience across all screen sizes.",
    tech1: "React",
    tech2: "Tailwind",
    tech3: "Framer",
    tech4: "Vercel",
    keyFeature1: "Dynamic product pages rendered using React Router DOM.",
    keyFeature2: "Integrated search and filter across all categories.",
    keyFeature3: "Checkout button triggers animated truck loading.",
    keyFeature4: "State managed using React's Context API system.",
    challenge: "The main challenge was using Context API and setting up dynamic routing, as it was my first complex project. Initially, I didn’t know how to structure the logic, but after exploring documentation and experimenting, I was able to implement both features successfully and gained confidence in React architecture.",
    role: "As the developer, I built this responsive e-commerce platform using React 19, implementing dynamic routing, state management with Context API, and interactive animations for a seamless user experience.",
    img1: "/gifsPort/e-commerce.gif",
    img2: "/mockups/ecom/laptop.webp",
    img3: "/mockups/ecom/Ipad.webp",
    img4: "/mockups/ecom/iPhone.webp",
  },
  "operon": {
    name: "Operon",
    year: "2026",
    image: "/mockups/operon/laptop.png",
    link: "https://operon-swart.vercel.app/",
    description: "Operon is an AI-powered multi-agent operations platform built for modern businesses to unify autonomous agents, assistant interfaces, workflow orchestration, and connected business tools within a scalable SaaS environment. The system integrates OpenClaw and includes modules for AI assistant interactions, agent activity monitoring, workflow automation, operations tracking, third-party integrations, authentication, and system settings. Designed to showcase enterprise-grade AI product capabilities, the platform demonstrates intelligent agent collaboration, streamlined operational management, and flexible automation for complex business processes across organizations at scale globally.",
    role: "I was responsible for architecting and developing the full-stack AI SaaS platform, integrating OpenClaw, designing multi-agent workflows, building assistant and operations modules, implementing authentication, and structuring scalable APIs and automation systems.",
    tech1: "Next.js",
    tech2: "Node.js",
    tech3: "OpenClaw",
    tech4: "AI Workflow Automation",
    keyFeature1: "AI assistant interactions with autonomous multi-agent coordination.",
    keyFeature2: "Workflow orchestration for business process automation.",
    keyFeature3: "Operations tracking with integrations across connected tools.",
    keyFeature4: "Secure authentication, settings, and scalable SaaS architecture.",
    challenge: "The main challenge was coordinating multiple AI agents, assistant interactions, and workflow pipelines within a reliable SaaS architecture. Ensuring modular system design, secure integrations, consistent agent behavior, and scalable operations visibility required careful planning to support complex enterprise automation use cases reliably.",
    img1: "/mockups/operon/iphone.png",
    img2: "/mockups/operon/laptop.png",
    img3: "/mockups/operon/ipad.png",
    img4: "/mockups/operon/best2.png"
  },

"sofa-3d-configurator": {
  name: "3D Sofa Configurator",
  year: "2026",
  image: "/mockups/sofa-3d-configurator/laptop.png",
  link: "https://3d-furniture-configurator.vercel.app/configurator/model-1?fabric=texture-4",
  description: "The 3D Sofa Configurator is an interactive product customization system built for furniture e-commerce platforms to improve customer engagement and purchase confidence. Using advanced 3D rendering, customers can modify sofa textures, fabric colors, and leg styles while instantly seeing visual updates in real time. The system also includes an augmented reality preview that allows users to place the configured sofa inside their own living space before purchasing. Designed for smooth performance and seamless store integration, the configurator enhances product visualization and increases conversion rates.",
  role: "I designed and developed the interactive 3D configurator, implemented real-time rendering with Three.js, built customization logic, integrated AR preview capabilities, and optimized performance to ensure smooth product visualization across devices.",
  tech1: "Three.js",
  tech2: "ARKit",
  tech3: "JavaScript",
  tech4: "3D Rendering",
  keyFeature1: "Real-time sofa customization with dynamic textures and material updates.",
  keyFeature2: "Augmented reality preview to place sofas inside the user’s home.",
  keyFeature3: "Interactive configuration interface with instant visual feedback.",
  keyFeature4: "Optimized rendering pipeline for smooth e-commerce integration.",
  challenge: "The main challenge was delivering realistic 3D rendering while maintaining fast performance across devices and browsers. Integrating AR previews, material customization, and responsive camera controls required careful optimization to ensure seamless visualization and accurate product representation.",
  img1: "/mockups/sofa-3d-configurator/mockup.png",
  img2: "/mockups/sofa-3d-configurator/laptop.png",
  img3: "/mockups/sofa-3d-configurator/iphone.png",
  img4: "/mockups/sofa-3d-configurator/iphone.png"
},

"garage-configurator": {
  name: "3D Garage Configurator",
  year: "2026",
  image: "/mockups/garage-configurator/laptop.png",
  link: "https://garage-configurator.vercel.app/garage-configurator",
  description: "The 3D Garage Configurator is a high-performance interactive builder that allows users to design and customize garage structures directly in the browser using real-time 3D rendering. Built with Three.js, the system enables dynamic adjustments such as window placement, wall textures, flooring options, and material variations with immediate visual feedback. Users can switch between exterior and interior views, preview configurations in a live demo window, and monitor pricing updates through a built-in summary panel. Optimized for fast loading and smooth rendering, the configurator delivers an immersive customization experience.",
  role: "I designed and developed the interactive 3D configurator, implemented real-time rendering with Three.js, built the customization logic, optimized performance across browsers, and integrated dynamic pricing updates with responsive UI controls.",
  tech1: "Three.js",
  tech2: "JavaScript",
  tech3: "PlayCanvas",
  tech4: "3D Rendering",
  keyFeature1: "Real-time 3D garage customization with dynamic structural updates.",
  keyFeature2: "Interior and exterior viewing modes for detailed configuration previews.",
  keyFeature3: "Instant pricing updates based on selected customization options.",
  keyFeature4: "Optimized rendering pipeline for smooth cross-browser performance.",
  challenge: "The main challenge was delivering smooth real-time 3D rendering while supporting complex configuration changes without performance drops. Managing dynamic geometry updates, material switching, camera controls, and pricing calculations required careful optimization to maintain responsiveness and consistent visual performance.",
  img1: "/mockups/garage-configurator/mockup.png",
  img2: "/mockups/garage-configurator/laptop.png",
  img3: "/mockups/garage-configurator/ipad.png",
  img4: "/mockups/garage-configurator/iphone.png"
},

  "factoryvision": {
    name: "FactoryVision",
    year: "2026",
    image: "/mockups/factoryvision/laptop.jpeg",
    link: "No Link.",
    description: "FactoryVision is an AI-powered object detection platform built for conveyor-belt factories to automate inspection, counting, and defect detection in fast-moving production environments. Using YOLOv26 and OpenCV, the system analyzes camera feeds to identify products, verify condition, and record traceable results in a local database. Designed with a fault-tolerant CCU-integrated architecture, it operates fully offline without internet and buffers events for later cloud synchronization. Built to reduce manual inspection, prevent quality escapes, and maintain reliable production visibility through resilient edge-to-cloud processing at industrial scale.",
    role: "I was responsible for designing and developing the edge-to-cloud detection pipeline, implementing offline local queuing and sync retries, integrating AI vision processing, and building reliable data flows for zero-loss industrial traceability.",
    tech1: "YOLOv26",
    tech2: "OpenCV",
    tech3: "Node.js",
    tech4: "Edge-to-Cloud Architecture",
    keyFeature1: "Real-time object detection, counting, and defect analysis on conveyor belts.",
    keyFeature2: "Offline-capable architecture with local buffering and event persistence.",
    keyFeature3: "Automatic cloud synchronization with retry logic after connectivity restoration.",
    keyFeature4: "Traceable inspection records with alerting for defective product events.",
    challenge: "The main challenge was building a fault-tolerant vision pipeline that could operate fully offline without losing inspection data. Coordinating real-time detection, local database writes, buffered event queues, cloud sync retries, and production alerts required careful architecture to ensure traceability and uninterrupted factory operations.",
    img1: "/mockups/factoryvision/mockup.jpeg",
    img2: "/mockups/factoryvision/laptop.jpeg",
    img3: "/mockups/factoryvision/ipad.jpeg",
    img4: "/mockups/factoryvision/iphone.jpeg"
  },


  "autonomyops-ai": {
    name: "AutonomyOps AI",
    year: "2026",
    image: "/mockups/autonomyops-ai/laptop.png",
    link: "https://autonomy-ops-ai.vercel.app/",
    description: "AutonomyOps AI is a privacy-first autonomous multi-agent operations platform built to support solo restaurant founders with round-the-clock business management. The system uses specialized AI agents to coordinate marketing, finances, social media, advertising, and campaign strategies through secure workflows and intelligent automation. By analyzing data from POS systems, ad platforms, and customer engagement channels, the platform generates decisions, automates reporting, and recommends actions. Designed for daily operations, it includes safety controls, approval checkpoints, monitoring, and secure integrations for efficient restaurant management.",
    role: "I was responsible for designing and developing the full-stack AI system, orchestrating multi-agent workflows, integrating restaurant data sources, implementing secure approvals and monitoring, and building automation pipelines for operational decision-making reliability.",
    tech1: "Next.js",
    tech2: "Node.js",
    tech3: "OpenAI SDK",
    tech4: "Multi-Agent Systems",
    keyFeature1: "Specialized AI agents for marketing, finance, advertising, and social operations.",
    keyFeature2: "Privacy-first architecture with secure integrations and approval checkpoints.",
    keyFeature3: "Automated reporting and decision support using restaurant data sources.",
    keyFeature4: "24/7 monitoring and workflow automation for reliable restaurant management.",
    challenge: "The primary challenge was building a privacy-first multi-agent system that could safely automate critical restaurant operations without sacrificing control. Coordinating reliable agent collaboration, approval checkpoints, secure data integrations, and continuous monitoring required careful architecture to ensure trustworthy decisions and uninterrupted day-to-day execution.",
    img1: "/mockups/autonomyops-ai/mockup.png",
    img2: "/mockups/autonomyops-ai/laptop.png",
    img3: "/mockups/autonomyops-ai/ipad.png",
    img4: "/mockups/autonomyops-ai/iphone.png"
  },

  "orion-workspace": {
    name: "Orion Workspace",
    year: "2026",
    image: "/mockups/orion-workspace/laptop.png",
    link: "https://orion-workspace-frontend.vercel.app",
    description: "Orion Workspace is a structured project management platform built for high-performance team collaboration, similar to ClickUp. Developed for a South African client, the system enables teams to organize workflows through dedicated zones such as Brain Dump, Top Priority, Agenda Zone, Status Badges, Tools, and Location tracking. The platform implements role-based access control, allowing administrators to monitor individual dashboards and maintain operational visibility. Deployed on a Contabo Ubuntu production server using industry best practices, the system ensures reliability, security, and scalable performance for growing teams.",
    role: "I was responsible for developing the complete full-stack system, implementing role-based access control with hierarchical admin dashboards, designing modular workflow sections, and deploying the platform securely on a Contabo Ubuntu production environment.",
    tech1: "Next.js",
    tech2: "Node.js",
    tech3: "RBAC System",
    tech4: "Ubuntu Deployment",
    keyFeature1: "Role-based dashboards with admin-level visibility.",
    keyFeature2: "Modular workflow zones including Brain Dump and Priority tracking.",
    keyFeature3: "Status badge system for task categorization.",
    keyFeature4: "Secure production deployment on Contabo Ubuntu server.",
    challenge: "The primary focus was architecting a scalable productivity system with strict permission boundaries and structured workflow logic. Designing modular sections, maintaining data consistency across dashboards, and deploying securely to a production server ensured enterprise-level reliability.",
    img1: "/gifsPort/orion-workspace.gif",
    img2: "/mockups/orion-workspace/laptop.png",
    img3: "/mockups/orion-workspace/ipad.png",
    img4: "/mockups/orion-workspace/iphone.png",
  },

  "skill-ai-scan": {
    name: "Skill AI Scan",
    year: "2026",
    image: "/mockups/skill-ai-scan/laptop.png",
    link: "https://skill-scan-ai-frontend.vercel.app",
    description: "Skill AI Scan is an AI-powered CV screening platform built to streamline and automate the hiring workflow for HR teams. The system allows recruiters to paste candidate CVs, define custom evaluation criteria, and leverage intelligent AI analysis to shortlist the most relevant profiles instantly. Designed with a multi-tenant architecture, each tenant operates with its own isolated database, custom domain, and white-labeled interface. Built using a Next.js frontend and Node.js backend with OpenAI integration, the platform ensures scalable performance, secure data separation, and enterprise-ready deployment for organizations.",
    role: "I was responsible for designing and developing the full-stack multi-tenant architecture, implementing tenant-level database isolation, integrating OpenAI-powered CV analysis, and building a scalable white-labeled frontend with secure authentication and API-driven workflows.",
    tech1: "Next.js",
    tech2: "Node.js",
    tech3: "OpenAI SDK",
    tech4: "Multi-Tenant Architecture",
    keyFeature1: "AI-driven CV evaluation based on customizable hiring criteria.",
    keyFeature2: "Tenant-level database isolation for secure data separation.",
    keyFeature3: "White-label support with custom domains per tenant.",
    keyFeature4: "Scalable API architecture for concurrent recruitment workflows.",
    challenge: "The core focus was architecting a scalable multi-tenant system that ensures strict data isolation while maintaining performance and flexibility. Implementing tenant-aware routing, secure authentication boundaries, and AI processing pipelines required careful system design to support commercial deployment across multiple organizations.",
    img1: "/gifsPort/skill-ai-scan.gif",
    img2: "/mockups/skill-ai-scan/laptop.png",
    img3: "/mockups/skill-ai-scan/ipad.png",
    img4: "/mockups/skill-ai-scan/iphone.png",
  },

  "asli-ai-monitor": {
    name: "AsliAIMonitor",
    year: "2026",
    image: "/mockups/asli-ai-monitor/laptop.png",
    link: "https://asli-ai-monitor-1.vercel.app",
    description: "AsliAIMonitor is an AI-powered teacher attendance and verification system designed for schools to ensure accountability and transparency. Students or parents can upload classroom photos when a teacher is absent, and the system verifies authenticity using AI-powered image validation. Submissions are restricted within a 120-meter geofenced radius and limited to official school hours to prevent misuse. The platform also automatically marks attendance when a teacher enters the school’s designated geofence area. Powered by the Gemini SDK and geospatial validation logic, the system combines AI verification with location intelligence for secure and reliable monitoring.",
    role: "I was responsible for developing the complete full-stack system, integrating Gemini SDK for AI-based image verification, implementing geofencing logic for radius and time restrictions, and building secure APIs and frontend workflows to ensure reliable attendance automation.",
    tech1: "Node.js",
    tech2: "Next.js",
    tech3: "Gemini SDK",
    tech4: "Geofencing System",
    keyFeature1: "AI-based image authenticity verification for absence reports.",
    keyFeature2: "120-meter geofenced submission restriction.",
    keyFeature3: "Automatic attendance marking via geofence detection.",
    keyFeature4: "Time-based validation limited to official school hours.",
    challenge: "The core focus was designing a secure system that prevents misuse while maintaining accuracy. Implementing geospatial boundaries, time-based restrictions, and AI verification required careful coordination between frontend validation, backend logic, and real-time location handling to ensure trustworthy attendance tracking.",
    img1: "/gifsPort/asli-ai-monitor.gif",
    img2: "/mockups/asli-ai-monitor/laptop.png",
    img3: "/mockups/asli-ai-monitor/ipad.png",
    img4: "/mockups/asli-ai-monitor/iphone.png",
  },


  "neighbourly-marketplace": {
    name: "Neighbourly Marketplace",
    year: "2025",
    image: "/mockups/neighbourly/laptop.png",
    link: "https://neighbourly-f.vercel.app/",
    description: "Neighbourly is a hyper-local marketplace platform designed to connect community members for exchanging services, tools, and skills. As the Full-Stack Developer, I built the Fastify and Node.js backend alongside a dynamic Next.js frontend, evolving the system from a neighborhood MVP into a scalable multi-city architecture. Users can create listings, discover nearby providers using radius-based queries, and coordinate bookings in real time. The platform integrates authentication, RBAC, caching, and messaging to ensure performance, reliability, and secure community interactions.",
    tech1: "Node.js",
    tech2: "Fastify",
    tech3: "Next.js",
    tech4: "PostgreSQL",
    keyFeature1: "Radius-based service discovery with geospatial queries.",
    keyFeature2: "Role-Based Access Control with structured permissions.",
    keyFeature3: "Real-time booking and messaging system.",
    keyFeature4: "Caching and optimized read/write handling for scale.",
    challenge: "As the sole Full-Stack Developer, I was responsible for architecting both backend and frontend systems with scalability in mind. I focused on clean API design, structured database modeling, and performance optimization to ensure the platform could evolve from MVP to high-concurrency production architecture.",
    role: "I was responsible for architecting and developing the complete full-stack system, building the backend with Node.js and Fastify, designing scalable APIs and database schemas, and implementing the Next.js frontend with role-based dashboards, real-time features, and geospatial service discovery.",
    img1: "/gifsPort/neighbourly.gif",
    img2: "/mockups/neighbourly/laptop.png",
    img3: "/mockups/neighbourly/ipad.png",
    img4: "/mockups/neighbourly/iphone.png",
  },


  "zarghab-real-estate": {
    name: "Real-Estate",
    year: "2025",
    image: "/projects/real.webp",
    link: "https://zarghab-real-estate.vercel.app/",
    description: "I built a real estate plot management system using Next.js and Tailwind CSS. This sleek, responsive web app replaces traditional, clunky tools by providing dynamic admin control, real-time updates, and PDF export functionality. It supports full CRUD without page reloads and role-based dashboards for better user experience. The smart filtering feature allows quick access to plots based on category or name. A simulated backend via MockAPI added realism. This project blends modern frontend tech with practical real estate workflows, showcasing how to create scalable tools for agencies, agents, or internal company use.",
    tech1: "Next.js",
    tech2: "React.js",
    tech3: "Tailwind CSS",
    tech4: "Framer-Motion",
    keyFeature1: "Role-based dashboards for admins and regular users.",
    keyFeature2: "CRUD operations with real-time updates using MockAPI.",
    keyFeature3: "Smart filters for instant plot search by name or type.",
    keyFeature4: "Client-side PDF export for bookings and receipts.",
    challenge: "This was my first project in Next.js, and I was new to SSR, ISR, and CSR concepts. Handling so many pages while learning these rendering methods was overwhelming. It was also my first time working with an API and implementing full CRUD operations, which made the experience very educational.",
    role: "I was responsible for architecting and developing the complete full-stack system, building the backend with Node.js and Fastify, designing scalable APIs and database schemas, and implementing the Next.js frontend with role-based dashboards, real-time features, and geospatial service discovery.",
    img1: "/gifsPort/real-estate.gif",
    img2: "/mockups/real-estate/laptop.webp",
    img3: "/mockups/real-estate/Ipad.webp",
    img4: "/mockups/real-estate/iPhone.webp",

  },
  "ezy-logistics": {
    name: "EZY Logistics",
    year: "2025",
    image: "/projects/EZY.webp",
    link: "https://fulfillezy.com/",
    description: "This project involved designing and developing a high-performance website for a 3PL logistics service offered by a company, where I work as a front-end developer. The goal was to create a visually impressive and highly interactive user experience to better reflect the modern capabilities of the company. To achieve this, I integrated an interactive 3D model using Three.js, which added depth and visual storytelling to the site. The website was optimized for speed and responsiveness, ensuring a smooth experience across all devices. By combining clean UI design with immersive visuals, the project successfully delivered a strong digital presence that appeals to both clients and partners.",
    tech1: "Next.js",
    tech2: "React.js",
    tech3: "Three.js",
    tech4: "Framer-Motion",
    keyFeature1: " Created immersive 3D visuals using powerful Three.js library.",
    keyFeature2: "Optimized entire website for speed, SEO, and responsiveness.",
    keyFeature3: "Designed modern UI reflecting brand's identity.",
    keyFeature4: "Added 3D ship model matching 3PL logistics service theme.",
    challenge: "This project was straightforward for me, with no significant challenges encountered. My prior experience with animations and performance optimization allowed me to implement smooth transitions and 3D interactions efficiently, even across different devices and screen sizes.",
    role: "As the front-end developer, I designed and developed this high-performance website for a 3PL logistics company, integrating 3D models with Three.js and optimizing for speed and responsiveness across devices.",
    img1: "/gifsPort/ezy.gif",
    img2: "/mockups/ezzy/laptop.webp",
    img3: "/mockups/ezzy/Ipad.webp",
    img4: "/mockups/ezzy/iPhone.webp",

  },
  "book-slider": {
    name: "3D Book",
    year: "2025",
    image: "/projects/VR.webp",
    link: "https://virtual-reality-chi.vercel.app/",
    description: "This project involved creating a unique, interactive 3D book experience using Three.js and React Three Fiber. The main highlight was the realistic sliding animation and the personalized engraving of my name on both the front and back covers. It pushed me creatively and technically, forcing me to explore 3D concepts and animation workflows. The result was a smooth, immersive experience with clean UI and a touch of personality. This was a big leap from traditional 2D interfaces, reflecting my commitment to exploring new technologies and constantly leveling up as a developer through real-world challenges.",
    tech1: "Three.js",
    tech2: "React.js",
    tech3: "R3F",
    tech4: "Tailwind CSS",
    keyFeature1: "Built a fully interactive 3D book using Three.js and React Three Fiber framework.",
    keyFeature2: "Engraved my name onto the front and back covers for a personal touch.",
    keyFeature3: "Styled clean and responsive UI using Tailwind CSS with a modern layout approach.",
    keyFeature4: "Achieved smooth and realistic 3D page slider transitions for immersive user interaction.",
    challenge: "This was my first time working with 3D and React Three Fiber. Understanding camera angles, lighting, and mesh interactions was difficult at first. I spent hours watching tutorials and debugging Three.js quirks. It was challenging but incredibly rewarding to turn a 3D concept into something smooth, personalized, and fully interactive.",
    role: "I developed this interactive 3D book experience using Three.js and React Three Fiber, focusing on realistic animations and personalized engravings to create an immersive interface.",
    img1: "/gifsPort/book.gif",
    img2: "/mockups/3D-book/laptop.webp",
    img3: "/mockups/3D-book/Ipad.webp",
    img4: "/mockups/3D-book/iPhone.webp",

  },

  "soch-ai-chatbot": {
    name: "Soch AI Chatbot",
    year: "2025",
    image: "/mockups/soch/laptop.webp",
    link: "https://sochai.ai/",
    description: "Soch AI is an immersive landing page promoting a chatbot app similar to ChatGPT. Built with Three.js and Matter.js, it features dynamic 3D visuals and interactive physics-based animations where cards fall from the sky and scatter on impact. The layout emphasizes modern UI principles, responsive design, and playful interactivity. This project combines stunning visuals, practical performance, and real-time user engagement, encouraging downloads with an entertaining and highly creative interface that mimics real-world physics while delivering a futuristic digital experience. Every element was crafted with user behavior and experience in mind to maximize user retention and interactivity.",
    tech1: "Three.js",
    tech2: "React.js",
    tech3: "Matter.js",
    tech4: "Tailwind CSS",
    keyFeature1: "Interactive physics-based cards fall and scatter dynamically.",
    keyFeature2: "Three.js renders imported 3D models with precision.",
    keyFeature3: "Responsive UI optimized for desktop and mobile.",
    keyFeature4: "Landing page built to maximize user downloads.",
    challenge: "I faced a serious issue with capsule collisions. Despite trying many solutions, nothing worked. After posting on GitHub and StackOverflow, a senior engineer from San Francisco offered help. Together, we debugged and solved the physics problem, making the animations behave correctly. It taught me how to approach collaborative debugging and strengthened my problem-solving skills in real-world animation issues.",
    role: "I created this immersive landing page for Soch AI using Three.js and Matter.js, implementing physics-based animations and responsive design to maximize user engagement and downloads.",
    img1: "/gifsPort/soch ai.gif",
    img2: "/mockups/soch/laptop.webp",
    img3: "/mockups/soch/Ipad.webp",
    img4: "/mockups/soch/iPhone.webp",

  },

};
