export const projects = {

  "orion-workspace": {
    name: "Orion Workspace",
    year: "2026",
    image: "/mockups/orion-workspace/laptop.png",
    link: "https://orion-workspace-frontend.vercel.app",
    description: "Orion Workspace is a structured project management platform built for high-performance team collaboration, similar to ClickUp. Developed for a South African client, the system enables teams to organize workflows through dedicated zones such as Brain Dump, Top Priority, Agenda Zone, Status Badges, Tools, and Location tracking. The platform implements role-based access control, allowing administrators to monitor individual dashboards and maintain operational visibility. Deployed on a Contabo Ubuntu production server using industry best practices, the system ensures reliability, security, and scalable performance for growing teams.",
    role: "I was responsible for developing the complete full-stack system, implementing role-based access control with hierarchical admin dashboards, designing modular workflow sections, and deploying the platform securely on a Contabo Ubuntu production environment.",
    tech1: "Next.js",
    tech2: "Node.js",
    tech3: "RBAC System",
    tech4: "Ubuntu Deployment",
    keyFeature1: "Role-based dashboards with admin-level visibility.",
    keyFeature2: "Modular workflow zones including Brain Dump and Priority tracking.",
    keyFeature3: "Status badge system for task categorization.",
    keyFeature4: "Secure production deployment on Contabo Ubuntu server.",
    challenge: "The primary focus was architecting a scalable productivity system with strict permission boundaries and structured workflow logic. Designing modular sections, maintaining data consistency across dashboards, and deploying securely to a production server ensured enterprise-level reliability.",
    img1: "/gifsPort/orion-workspace.gif",
    img2: "/mockups/orion-workspace/laptop.png",
    img3: "/mockups/orion-workspace/ipad.png",
    img4: "/mockups/orion-workspace/iphone.png",
  },

  "asli-ai-monitor": {
    name: "AsliAIMonitor",
    year: "2026",
    image: "/mockups/asli-ai-monitor/laptop.png",
    link: "https://asli-ai-monitor-1.vercel.app",
    description: "AsliAIMonitor is an AI-powered teacher attendance and verification system designed for schools to ensure accountability and transparency. Students or parents can upload classroom photos when a teacher is absent, and the system verifies authenticity using AI-powered image validation. Submissions are restricted within a 120-meter geofenced radius and limited to official school hours to prevent misuse. The platform also automatically marks attendance when a teacher enters the school’s designated geofence area. Powered by the Gemini SDK and geospatial validation logic, the system combines AI verification with location intelligence for secure and reliable monitoring.",
    role: "I was responsible for developing the complete full-stack system, integrating Gemini SDK for AI-based image verification, implementing geofencing logic for radius and time restrictions, and building secure APIs and frontend workflows to ensure reliable attendance automation.",
    tech1: "Node.js",
    tech2: "Next.js",
    tech3: "Gemini SDK",
    tech4: "Geofencing System",
    keyFeature1: "AI-based image authenticity verification for absence reports.",
    keyFeature2: "120-meter geofenced submission restriction.",
    keyFeature3: "Automatic attendance marking via geofence detection.",
    keyFeature4: "Time-based validation limited to official school hours.",
    challenge: "The core focus was designing a secure system that prevents misuse while maintaining accuracy. Implementing geospatial boundaries, time-based restrictions, and AI verification required careful coordination between frontend validation, backend logic, and real-time location handling to ensure trustworthy attendance tracking.",
    img1: "/gifsPort/asli-ai-monitor.gif",
    img2: "/mockups/asli-ai-monitor/laptop.png",
    img3: "/mockups/asli-ai-monitor/ipad.png",
    img4: "/mockups/asli-ai-monitor/iphone.png",
  },


  "neighbourly-marketplace": {
    name: "Neighbourly Marketplace",
    year: "2025",
    image: "/mockups/neighbourly/laptop.png",
    link: "https://neighbourly-f.vercel.app/",
    description: "Neighbourly is a hyper-local marketplace platform designed to connect community members for exchanging services, tools, and skills. As the Full-Stack Developer, I built the Fastify and Node.js backend alongside a dynamic Next.js frontend, evolving the system from a neighborhood MVP into a scalable multi-city architecture. Users can create listings, discover nearby providers using radius-based queries, and coordinate bookings in real time. The platform integrates authentication, RBAC, caching, and messaging to ensure performance, reliability, and secure community interactions.",
    tech1: "Node.js",
    tech2: "Fastify",
    tech3: "Next.js",
    tech4: "PostgreSQL",
    keyFeature1: "Radius-based service discovery with geospatial queries.",
    keyFeature2: "Role-Based Access Control with structured permissions.",
    keyFeature3: "Real-time booking and messaging system.",
    keyFeature4: "Caching and optimized read/write handling for scale.",
    challenge: "As the sole Full-Stack Developer, I was responsible for architecting both backend and frontend systems with scalability in mind. I focused on clean API design, structured database modeling, and performance optimization to ensure the platform could evolve from MVP to high-concurrency production architecture.",
    role: "I was responsible for architecting and developing the complete full-stack system, building the backend with Node.js and Fastify, designing scalable APIs and database schemas, and implementing the Next.js frontend with role-based dashboards, real-time features, and geospatial service discovery.",
    img1: "/gifsPort/neighbourly.gif",
    img2: "/mockups/neighbourly/laptop.png",
    img3: "/mockups/neighbourly/ipad.png",
    img4: "/mockups/neighbourly/iphone.png",
  },


};
